import type { Product } from "@/types";

export const products: Product[] = [
  {
    id: "de-standard-01",
    origin: "german",
    originLabel: "ألمانيا",
    originCode: "DE",
    design: "standard",
    name: "DXL Hybrid Implants",
     image: "/products/DXLhybrid.jpeg",
    subtitle: "Standard تصميم",
    description: "هندسة دقيقة وثبات عالي، مناسبة لمعظم الحالات مع عمر استخدام ممتد.",
    // number: "#01",
  },
  {
    id: "de-aggressive-02",
    origin: "german",
    originLabel: "ألمانيا",
    originCode: "DE",
    design: "aggressive",
    name: " DXL Implants",
     image: "/products/DXL.jpeg",
    subtitle: "Aggressive تصميم",
    description: "ثبات أولي استثنائي للحالات المعقدة وكثافة العظم المتخفضة بفضل الأسنان العميقة.",
    // number: "#02",
  },
 
  {
    id: "kr-aggressive-04",
    origin: "korean",
    originLabel: "كوريا",
    originCode: "KR",
    design: "aggressive",
    name: "Biotem implants",
     image: "/products/Biotem.jpeg",
    subtitle: "Aggressive تصميم",
    description: "أسنان حلزونية حادة لاندماج عظمي سريع مع نتائج مثبتة .",
    // number: "#04",
  },
  {
    id: "eg-standard-05",
    origin: "egyptian",
    originLabel: "مصر",
    originCode: "EG",
    design: "standard",
    name: "Dual implants",
    image: "/products/dual.jpeg",
    subtitle: "Standard تصميم",
    description: "تصنيع محلي بمعايير دولية، حل اقتصادي موثوق للحالات الشائعة.",
    // number: "#05",
  },
  {
    id: "eg-aggressive-06",
    origin: "egyptian",
    originLabel: "مصر",
    originCode: "EG",
    design: "aggressive",
    name: "Zi implants",
   image: "/products/zi.jpeg",
    subtitle: "Aggressive تصميم",
    description: "أداء قوي بسعر مناسب، مصمم خصيصاً للحالات التي تتطلب ثبات فوري.",
   
  },
];
